### ISSUE TITLE
ADelay & ATapeDelay missing from /src

### ISSUE THREAD

**Issue by SteveRussell33** [LOGUNIVPM/VCVBook#1]
Both modules defined in manifest but sources are missing

**Comment by LOGUNIVPM** [comment]
Thank you for reporting. Since the book is not out yet I just uploaded the material and I still have to conduct a final check. Today I'm out of office but I did the fix to the manifest from my mobile. Those modules will not appear in the ABC.

**Comment by SteveRussell33** [comment]
OK noted, thanks for the reply.

**Comment by pgatt** [comment]
That's a shame - was looking to see how the tape delay worked.

**Comment by LOGUNIVPM** [comment]
Thank you pgatt and sorry for this. My current plan is to release these in a future extensions of the ABC plugin together with an extra online chapter, but I don't foresee it in the near future. If more people ask I could add something to the LOGinstruments plugin but in that case I would provide no support text. Best regards
