### ISSUE TITLE
ABC Harmonics Scope?

### ISSUE THREAD

**Issue by djpeterso23662** [LOGUNIVPM/VCVBook#2]
Hello Leonardo!  I have been enjoying your book very much!  (Purchased from Amazon in the US in paperback, if you are collecting data points.)  It is a big help.  

A scope for viewing harmonics was mentioned as being part of the ABC package in the chapter I re-read tonight.  I have hunted around for it but not found it.  Am I missing something?  

Thanks for your time!

David

**Comment by LOGUNIVPM** [comment]
Dear David,
thank you for the comment. I ended up not including it, but cleaned a bit the one I already developed in the LOGInstruments plugin (here: https://library.vcvrack.com/LOGinstruments/Speck).
Hope this helps and thank you for pointing this to me, I will add it to the Errata soon. What is the page where I wrote this?

**Comment by WimBast** [comment]
Dear Leonardo,

It is written on page 88, paragraph 3.6.4, the second sentence.
I had the same question.

Your book is very nice! Very inspiring.

thanks,
Wim

Op ma 20 jul. 2020 om 17:01 schreef Leonardo Gabrielli <
notifications@github.com>:

**Comment by LOGUNIVPM** [comment]
Thank you, just for clarity, I want to share my choice: I wanted all ABC modules to be carefully explained in the book. The FFT visualization module is very complex to explain and is not really synthesis-related therefore I opted it out, leaving the module in LOGinstruments, which anyway is open-source. 
I will acknowledge you both for the notification in the errata ;)

**Comment by djpeterso23662** [comment]
Thank you, Leonardo!  I concur with your decision to exclude the viz
module, and appreciate you taking time to document your thoughts.  Perhaps
a bonus, online-only chapter could discuss it some day.

David
