### ISSUE TITLE
Expected output for Modal modules

### ISSUE THREAD

**Issue by mpicard** [LOGUNIVPM/VCVBook#4]
Hey I am not sure if I correctly programmed the modal modules and I was wondering if you have a video and or explanation and or patches that could demonstrate the proper use and output, it seems there is no "excitation" in my system but I spent some time debugging and comparing the code and I can't figure out what the expected output should be.

**Comment by LOGUNIVPM** [comment]
Hi, I have pushed 3 patches that make use of the AModal modules. As you can see they expect the excitation as an external input. There is no internal excitation to leave maximum flexibility and modularity. As you can see it can be noise or a short pulse. 
If you have the book you'll find more information there.
